const navItems=['Home','Vault','Generator','Security','Sharing','Activity','Settings'];
const seed=[{name:'GitHub',user:'alex@private.dev',url:'github.com',type:'Login'},{name:'Proton Mail',user:'alex@pm.me',url:'proton.me',type:'Login'},{name:'Cloudflare',user:'work-admin',url:'cloudflare.com',type:'Login'}];
let items=JSON.parse(localStorage.getItem('aegis-items')||'null')||seed,page='Home';
const nav=document.querySelector('#nav'),content=document.querySelector('#content'),title=document.querySelector('#title');
const icons={Home:'⌂',Vault:'◇',Generator:'✦',Security:'◉',Sharing:'♧',Activity:'↻',Settings:'⚙'};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function renderNav(){nav.innerHTML=navItems.map(n=>`<button class="nav ${n===page?'active':''}" data-page="${n}">${icons[n]} &nbsp; ${n}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function rows(list=items){return list.length?list.map(x=>`<div class="item"><div class="favicon">${esc(x.name[0]||'?')}</div><div><b>${esc(x.name)}</b><small>${esc(x.user||'No username')} · ${esc(x.url||'No website')}</small></div><span class="badge good">Protected</span></div>`).join(''):'<div class="empty">No matching vault items</div>'}
function home(){return `<div class="grid"><article class="card score"><div class="card-title"><h3>Protection score</h3><span class="badge good">Excellent</span></div><div class="score-num">91</div><div class="muted">Your security posture looks strong.</div><div class="bar"><i></i></div><small class="muted">2 recommendations available</small></article><article class="card quick"><div class="card-title"><h3>Quick actions</h3></div><div class="quick-grid"><button class="quick-btn" onclick="openAdd()"><b>＋ Add login</b><span>Save a new account</span></button><button class="quick-btn" onclick="go('Generator')"><b>✦ Generate</b><span>Create a strong password</span></button><button class="quick-btn" onclick="go('Security')"><b>◉ Security check</b><span>Review risks privately</span></button><button class="quick-btn" onclick="go('Sharing')"><b>♧ Secure share</b><span>Encrypted sharing controls</span></button></div></article><article class="card recent"><div class="card-title"><h3>Recent items</h3><button class="ghost" onclick="go('Vault')">View vault</button></div><div class="list">${rows(items.slice(0,4))}</div></article><article class="card devices"><div class="card-title"><h3>Trusted devices</h3><span class="badge">2 active</span></div><div class="item"><div class="favicon">W</div><div><b>Windows PC</b><small>Active now</small></div></div><div class="item"><div class="favicon">A</div><div><b>Android phone</b><small>Recently synced</small></div></div></article></div>`}
function vault(){return `<div class="vault-toolbar"><input class="search" id="search" placeholder="Search your vault…"><button class="primary" onclick="openAdd()">＋ Add</button></div><article class="card vault-card"><div class="card-title"><h3>All items</h3><span class="muted">${items.length} items</span></div><div id="vaultRows" class="list">${rows()}</div></article>`}
function generator(){return `<div class="page-grid"><article class="card"><p class="eyebrow">LOCAL GENERATOR</p><h2>Password generator</h2><p class="muted" style="margin-top:8px">Generated locally with the browser cryptographic RNG.</p><div id="generated" class="generator">Press Generate</div><label>Length <span id="len">24</span><input class="range" id="length" type="range" min="12" max="64" value="24"></label><div class="toolbar"><button class="primary" onclick="makePassword()">Generate</button><button class="ghost" onclick="copyGenerated()">Copy</button></div></article><article class="card"><h3>Presets</h3><div class="list"><div class="setting"><span>Strong login</span><span class="badge">24 chars</span></div><div class="setting"><span>Maximum</span><span class="badge">48 chars</span></div><div class="setting"><span>PIN</span><span class="badge">6 digits</span></div></div></article></div>`}
function security(){return `<div class="page-grid"><article class="card"><div class="card-title"><h2>Security Guardian</h2><span class="badge good">91 / 100</span></div><div class="metric-grid"><div class="metric"><strong>0</strong><span>Compromised</span></div><div class="metric"><strong>1</strong><span>Reused password</span></div><div class="metric"><strong>2</strong><span>Missing 2FA</span></div><div class="metric"><strong>3</strong><span>Passkey upgrades</span></div></div></article><article class="card"><h3>Recommendations</h3><div class="list"><div class="setting"><div><b>Enable 2FA</b><small class="muted">2 accounts</small></div><span class="badge warn">Review</span></div><div class="setting"><div><b>Use passkeys</b><small class="muted">3 supported accounts</small></div><span class="badge">Upgrade</span></div></div></article></div>`}
function sharing(){return `<article class="card vault-card"><p class="eyebrow">END-TO-END ENCRYPTED</p><h2>Secure sharing</h2><p class="muted" style="margin-top:9px">Share individual vault items with expiration, view limits and revocation. Server integration will activate when the Oracle API is connected.</p><div class="metric-grid" style="margin-top:22px"><div class="metric"><strong>0</strong><span>Active shares</span></div><div class="metric"><strong>0</strong><span>Family members</span></div></div></article>`}
function activity(){return `<article class="card vault-card"><div class="card-title"><h2>Activity</h2><span class="badge">Privacy-safe</span></div><div class="list"><div class="item"><div class="favicon">✓</div><div><b>Vault unlocked</b><small>This browser · current session</small></div><span class="badge good">Expected</span></div><div class="item"><div class="favicon">↻</div><div><b>Local vault ready</b><small>No cloud connection configured</small></div><span class="badge">Local</span></div></div></article>`}
function settings(){return `<article class="card vault-card"><p class="eyebrow">PRIVACY & SECURITY</p><h2>Settings</h2><div class="setting"><div><b>Auto-lock</b><small class="muted">Lock after inactivity</small></div><div class="toggle"><i></i></div></div><div class="setting"><div><b>Clipboard clearing</b><small class="muted">Clear copied secrets automatically</small></div><div class="toggle"><i></i></div></div><div class="setting"><div><b>Privacy mode</b><small class="muted">Hide sensitive values by default</small></div><div class="toggle"><i></i></div></div><div class="setting"><div><b>Sync backend</b><small class="muted">Oracle VM encrypted API</small></div><span class="badge warn">Not connected</span></div></article>`}
function render(){renderNav();title.textContent=page==='Home'?'Overview':page;content.innerHTML=({Home:home,Vault:vault,Generator:generator,Security:security,Sharing:sharing,Activity:activity,Settings:settings}[page])();if(page==='Vault')document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelector('#vaultRows').innerHTML=rows(items.filter(x=>(x.name+x.user+x.url).toLowerCase().includes(q)))};if(page==='Generator'){const r=document.querySelector('#length');r.oninput=()=>document.querySelector('#len').textContent=r.value}}
window.go=p=>{page=p;render()};window.openAdd=()=>document.querySelector('#modal').classList.remove('hidden');
window.makePassword=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=';const len=+(document.querySelector('#length')?.value||24),a=new Uint32Array(len);crypto.getRandomValues(a);document.querySelector('#generated').textContent=[...a].map(n=>chars[n%chars.length]).join('')};
window.copyGenerated=async()=>{const v=document.querySelector('#generated').textContent;if(v==='Press Generate')return;await navigator.clipboard.writeText(v);toast('Copied — clear clipboard after use')};
document.querySelector('#add').onclick=openAdd;document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.add('hidden');document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};
document.querySelector('#generate').onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=';let a=new Uint32Array(24);crypto.getRandomValues(a);document.querySelector('#password').value=[...a].map(n=>chars[n%chars.length]).join('')};
document.querySelector('#itemForm').onsubmit=e=>{e.preventDefault();items.unshift({name:document.querySelector('#name').value,user:document.querySelector('#username').value,url:document.querySelector('#website').value,type:'Login'});localStorage.setItem('aegis-items',JSON.stringify(items));e.target.reset();document.querySelector('#modal').classList.add('hidden');page='Vault';render();toast('Saved to this browser')};
document.querySelector('#lock').onclick=()=>document.querySelector('#lockscreen').classList.remove('hidden');document.querySelector('#unlock').onclick=()=>document.querySelector('#lockscreen').classList.add('hidden');render();