const navItems=['Home','Vault','Generator','Security','Sharing','Activity','Settings'];
const seed=[{name:'GitHub',user:'alex@private.dev',url:'github.com'},{name:'Proton Mail',user:'alex@pm.me',url:'proton.me'},{name:'Cloudflare',user:'work-admin',url:'cloudflare.com'}];
let items=JSON.parse(localStorage.getItem('aegis-items')||'null')||seed; let page='Home';
const nav=document.querySelector('#nav'),content=document.querySelector('#content'),title=document.querySelector('#title');
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderNav(){nav.innerHTML=navItems.map(n=>`<button class="nav ${n===page?'active':''}" data-page="${n}">${({Home:'⌂',Vault:'◇',Generator:'✦',Security:'◉',Sharing:'♧',Activity:'↻',Settings:'⚙'})[n]} &nbsp; ${n}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function rows(){return items.map(x=>`<div class="item"><div class="favicon">${esc(x.name[0]||'?')}</div><div><b>${esc(x.name)}</b><small>${esc(x.user||'No username')} · ${esc(x.url||'No website')}</small></div><span class="badge">Protected</span></div>`).join('')}
function home(){return `<div class="grid"><article class="card score"><div class="card-title"><h3>Protection score</h3><span class="badge">Excellent</span></div><div class="score-num">91</div><div class="muted">Your vault is strongly protected.</div><div class="bar"><i></i></div><small class="muted">2 recommendations available</small></article><article class="card quick"><div class="card-title"><h3>Quick actions</h3></div><div class="quick-grid"><button class="quick-btn" onclick="openAdd()"><b>＋ Add login</b><span>Save a new account</span></button><button class="quick-btn" onclick="go('Generator')"><b>✦ Generate</b><span>Create a strong password</span></button><button class="quick-btn" onclick="go('Security')"><b>◉ Security check</b><span>Review risks privately</span></button><button class="quick-btn" onclick="go('Sharing')"><b>♧ Secure share</b><span>End-to-end encrypted</span></button></div></article><article class="card recent"><div class="card-title"><h3>Recent items</h3><button class="ghost" onclick="go('Vault')">View vault</button></div><div class="list">${rows()}</div></article><article class="card devices"><div class="card-title"><h3>Trusted devices</h3><span class="badge">3 active</span></div><div class="item"><div class="favicon">W</div><div><b>Windows PC</b><small>Active now</small></div></div><div class="item"><div class="favicon">A</div><div><b>Android phone</b><small>Synced 2m ago</small></div></div></article></div>`}
function vault(){return `<div class="vault-toolbar"><input class="search" id="search" placeholder="Search your encrypted vault…"><button class="primary" onclick="openAdd()">＋ Add</button></div><article class="card vault-card"><div class="card-title"><h3>All items</h3><span class="muted">${items.length} items</span></div><div id="vaultRows" class="list">${rows()}</div></article>`}
function generic(){const copy={Generator:['Password Generator','Create strong credentials locally.'],Security:['Security Guardian','Weak, reused and compromised credential checks stay privacy-first.'],Sharing:['Secure Sharing','Share selected secrets with expiration and revocation controls.'],Activity:['Activity','Security-relevant events without unnecessary sensitive logging.'],Settings:['Settings','Privacy mode, trusted devices, recovery and platform preferences.']}[page];return `<article class="card vault-card"><p class="eyebrow">AEGIS</p><h2>${copy[0]}</h2><p class="muted" style="margin-top:10px">${copy[1]}</p>${page==='Generator'?'<div style="margin-top:22px"><button class="primary" onclick="makePassword()">Generate password</button><h2 id="generated" style="margin-top:20px;font-family:monospace;word-break:break-all"></h2></div>':''}</article>`}
function render(){renderNav();title.textContent=page==='Home'?'Good evening':page;content.innerHTML=page==='Home'?home():page==='Vault'?vault():generic();if(page==='Vault'){document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelector('#vaultRows').innerHTML=items.filter(x=>(x.name+x.user+x.url).toLowerCase().includes(q)).map(x=>`<div class="item"><div class="favicon">${esc(x.name[0])}</div><div><b>${esc(x.name)}</b><small>${esc(x.user)} · ${esc(x.url)}</small></div><span class="badge">Protected</span></div>`).join('')}}}
window.go=p=>{page=p;render()};window.openAdd=()=>document.querySelector('#modal').classList.remove('hidden');window.makePassword=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*';let a=new Uint32Array(24);crypto.getRandomValues(a);document.querySelector('#generated').textContent=[...a].map(n=>chars[n%chars.length]).join('')};
document.querySelector('#add').onclick=openAdd;document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.add('hidden');document.querySelector('#generate').onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*';let a=new Uint32Array(20);crypto.getRandomValues(a);document.querySelector('#password').value=[...a].map(n=>chars[n%chars.length]).join('')};document.querySelector('#itemForm').onsubmit=e=>{e.preventDefault();items.unshift({name:document.querySelector('#name').value,user:document.querySelector('#username').value,url:document.querySelector('#website').value});localStorage.setItem('aegis-items',JSON.stringify(items));e.target.reset();document.querySelector('#modal').classList.add('hidden');page='Vault';render()};let locked=false;document.querySelector('#lock').onclick=e=>{locked=!locked;content.classList.toggle('locked',locked);e.target.textContent=locked?'Unlock':'⌘ Lock'};render();
