import React,{useEffect,useRef,useState}from'react';import{motion}from'motion/react';import{Check,ChevronRight,FolderKey,LoaderCircle}from'lucide-react';

export function RippleDistortion(){const ref=useRef(null);useEffect(()=>{const el=ref.current;if(!el)return;const move=e=>{const r=el.getBoundingClientRect();el.style.setProperty('--rx',((e.clientX-r.left)/r.width*100)+'%');el.style.setProperty('--ry',((e.clientY-r.top)/r.height*100)+'%')};window.addEventListener('pointermove',move,{passive:true});return()=>window.removeEventListener('pointermove',move)},[]);return <div ref={ref} className="ripple-distortion" aria-hidden><i/><i/><i/></div>}
export function CursorGrid(){return <div className="cursor-grid" aria-hidden/>}
export function TechText({children}){return <span className="tech-text" data-text={children}>{children}</span>}
export function SpecularButton({children,className='',...props}){return <motion.button whileTap={{scale:.98}} className={'specular '+className} {...props}><span>{children}</span><i aria-hidden/></motion.button>}
export function FolderFloat({label='Private vault',count=0}){return <motion.div className="folder-float" whileHover={{y:-8,rotate:-1}}><div className="folder-tab"/><FolderKey/><b>{label}</b><small>{count} protected items</small></motion.div>}
export function LatticeLoader({label='Securing session'}){return <div className="lattice-loader" role="status"><div>{Array.from({length:9},(_,i)=><i key={i}/>)}</div><span>{label}</span></div>}
export function HoldButton({children,onComplete,disabled=false}){const[t,setT]=useState(null),[holding,setHolding]=useState(false);const start=()=>{if(disabled)return;setHolding(true);setT(setTimeout(()=>{setHolding(false);onComplete?.()},900))};const stop=()=>{setHolding(false);if(t)clearTimeout(t)};return <button type="button" disabled={disabled} className={'hold-button '+(holding?'holding':'')} onPointerDown={start} onPointerUp={stop} onPointerLeave={stop}><span>{children}</span><i/></button>}
export function SwipeToast({message,onDone}){useEffect(()=>{const id=setTimeout(()=>onDone?.(),3600);return()=>clearTimeout(id)},[message,onDone]);return message?<motion.div drag="x" dragConstraints={{left:0,right:0}} onDragEnd={(_,x)=>Math.abs(x.offset.x)>80&&onDone?.()} initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}} className="swipe-toast"><Check/><span>{message}</span><small>swipe to dismiss</small></motion.div>:null}
export function GlassIcons({items}){return <div className="glass-icons">{items.map(({icon:I,label,onClick})=><button key={label} onClick={onClick}><span><I/></span><small>{label}</small></button>)}</div>}
export function LogoLoop(){return <div className="logo-loop"><div>{['WEB','ANDROID','iOS','WINDOWS','macOS','LINUX','CHROME','FIREFOX'].map(x=><span key={x}>{x}</span>)}</div></div>}
export function Dock({items,active,onSelect}){return <div className="dock">{items.map(({name,icon:I})=><motion.button whileHover={{y:-7,scale:1.06}} key={name} className={active===name?'active':''} onClick={()=>onSelect(name)} title={name}><I/><span>{name}</span></motion.button>)}</div>}
export function ProfileCard({profile,onEdit}){return <div className="identity-card"><div className="identity-avatar">{(profile?.displayName||profile?.email||'A')[0].toUpperCase()}</div><div><span className="kicker">AEGIS IDENTITY</span><h3>{profile?.displayName||'Private member'}</h3><p>{profile?.email}</p></div><button className="identity-edit" onClick={onEdit}>Edit profile <ChevronRight/></button></div>}
