import{argon2id}from'hash-wasm';
const te=new TextEncoder(),td=new TextDecoder();
const DB='aegis-vault-v1',STORE='vault',RECORD='primary';
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const db=()=>new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
async function get(){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(STORE),r=t.objectStore(STORE).get(RECORD);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error);t.oncomplete=()=>d.close()})}
async function put(v){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,RECORD);t.oncomplete=()=>{d.close();ok()};t.onerror=()=>no(t.error)})}
async function pbkdf2(password,salt){const material=await crypto.subtle.importKey('raw',te.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:600000},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function argonKey(password,salt){const raw=await argon2id({password,salt,parallelism:1,iterations:3,memorySize:65536,hashLength:32,outputType:'binary'});return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encrypt(key,value){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,te.encode(JSON.stringify(value)));return{iv:b64(iv),data:b64(data)}}
async function decrypt(key,box){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},key,unb64(box.data));return JSON.parse(td.decode(plain))}
async function wrapRaw(kek,raw){return encrypt(kek,{key:b64(raw)})}
async function unwrapRaw(kek,box){const v=await decrypt(kek,box);return unb64(v.key)}
async function vaultKey(raw){return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function vaultExists(){return!!(await get())}
export async function createVault(password,items=[]){const salt=crypto.getRandomValues(new Uint8Array(16)),raw=crypto.getRandomValues(new Uint8Array(32));const kek=await argonKey(password,salt),key=await vaultKey(raw);const wrappedKey=await wrapRaw(kek,raw),check=await encrypt(key,{aegis:'vault-check-v2'}),payload=await encrypt(key,items);await put({v:2,kdf:{name:'Argon2id',iterations:3,memorySize:65536,parallelism:1,salt:b64(salt)},wrappedKey,check,payload,revision:0});return{key,items}}
export async function unlockVault(password){const r=await get();if(!r)throw new Error('Vault is not initialized');try{if(r.v===1){const oldKey=await pbkdf2(password,unb64(r.kdf.salt));const check=await decrypt(oldKey,r.check);if(check.aegis!=='vault-check-v1')throw 0;const items=await decrypt(oldKey,r.payload),salt=crypto.getRandomValues(new Uint8Array(16)),raw=crypto.getRandomValues(new Uint8Array(32)),kek=await argonKey(password,salt),key=await vaultKey(raw);await put({v:2,kdf:{name:'Argon2id',iterations:3,memorySize:65536,parallelism:1,salt:b64(salt)},wrappedKey:await wrapRaw(kek,raw),check:await encrypt(key,{aegis:'vault-check-v2'}),payload:await encrypt(key,items),revision:Number(r.revision||0)});return{key,items,migrated:true}}const kek=await argonKey(password,unb64(r.kdf.salt)),raw=await unwrapRaw(kek,r.wrappedKey),key=await vaultKey(raw),check=await decrypt(key,r.check);if(check.aegis!=='vault-check-v2')throw 0;return{key,items:await decrypt(key,r.payload)}}catch{throw new Error('Incorrect master password')}}
export async function changeMasterPassword(currentPassword,newPassword){if(!newPassword||newPassword.length<12)throw new Error('New master password must be at least 12 characters');const r=await get();if(!r||r.v!==2)throw new Error('Vault must be upgraded before changing the master password');try{const oldKek=await argonKey(currentPassword,unb64(r.kdf.salt)),raw=await unwrapRaw(oldKek,r.wrappedKey),key=await vaultKey(raw),check=await decrypt(key,r.check);if(check.aegis!=='vault-check-v2')throw 0;const salt=crypto.getRandomValues(new Uint8Array(16)),newKek=await argonKey(newPassword,salt);r.kdf={name:'Argon2id',iterations:3,memorySize:65536,parallelism:1,salt:b64(salt)};r.wrappedKey=await wrapRaw(newKek,raw);await put(r);return true}catch{throw new Error('Current master password is incorrect')}}
export async function saveVault(key,items){const r=await get();if(!r)throw new Error('Vault is not initialized');r.payload=await encrypt(key,items);await put(r)}
export async function migrateLegacy(key,items){await saveVault(key,items);localStorage.removeItem('aegis-items-v2')}
export function prepareItem(item){const now=new Date().toISOString();return{...item,id:item.id||crypto.randomUUID(),updatedAt:item.updatedAt||now,mutationId:item.mutationId||crypto.randomUUID(),deletedAt:item.deletedAt||null}}
const stable=v=>v&&typeof v==='object'?Array.isArray(v)?v.map(stable):Object.fromEntries(Object.keys(v).sort().filter(k=>!['id','updatedAt','mutationId','deletedAt','deletedRevision'].includes(k)).map(k=>[k,stable(v[k])])):v;async function legacyId(item){const h=await crypto.subtle.digest('SHA-256',te.encode(JSON.stringify(stable(item))));return'legacy-'+[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32)}async function normalize(items){return Promise.all(items.map(async x=>({...x,id:x.id||await legacyId(x),updatedAt:x.updatedAt||'1970-01-01T00:00:00.000Z',mutationId:x.mutationId||'legacy',deletedAt:x.deletedAt||null})))}
export async function mergeRemoteEnvelope(key,envelope){const local=await get();if(!local||local.v!==2)throw new Error('Vault merge requires v2');const remote=JSON.parse(td.decode(unb64(envelope.ciphertext)));if(remote.v!==2)throw new Error('Remote vault format is incompatible');if(JSON.stringify(local.kdf)!==JSON.stringify(remote.kdf)||JSON.stringify(local.wrappedKey)!==JSON.stringify(remote.wrappedKey)||JSON.stringify(local.check)!==JSON.stringify(remote.check))throw new Error('Vault key wrapper changed on another device');let localItems=await decrypt(key,local.payload),remoteItems;try{remoteItems=await decrypt(key,remote.payload)}catch{throw new Error('Remote vault key changed')};localItems=await normalize(localItems);remoteItems=await normalize(remoteItems);const merged=new Map(),rank=x=>String(x.deletedAt||x.updatedAt||''),tie=x=>String(x.mutationId||'');for(const item of [...remoteItems,...localItems]){const prev=merged.get(item.id);if(!prev||rank(item)>rank(prev)||(rank(item)===rank(prev)&&tie(item)>tie(prev)))merged.set(item.id,item)}const items=[...merged.values()].sort((a,b)=>rank(b).localeCompare(rank(a)));const record={...local,payload:await encrypt(key,items),revision:Number(envelope.revision||0)};return{items,record}}
export async function stampDeletionRevision(key,id,revision){const r=await get();if(!r)return;const items=(await decrypt(key,r.payload)).map(x=>x.id===id&&x.deletedAt&&!x.deletedRevision?{...x,deletedRevision:revision}:x);r.payload=await encrypt(key,items);await put(r);return items}
export async function collectTombstones(key,minAckRevision){const r=await get();if(!r)return{items:[],removed:0};const before=await decrypt(key,r.payload),items=before.filter(x=>!(x.deletedAt&&x.deletedRevision&&Number(x.deletedRevision)<=Number(minAckRevision)));if(items.length!==before.length){r.payload=await encrypt(key,items);await put(r)}return{items,removed:before.length-items.length}}
export async function exportSyncEnvelope(){const r=await get();if(!r)return null;const body=r.v===2?{v:r.v,kdf:r.kdf,wrappedKey:r.wrappedKey,check:r.check,payload:r.payload}:{v:r.v,kdf:r.kdf,check:r.check,payload:r.payload};return{version:r.v,revision:Number(r.revision||0),updatedAt:new Date().toISOString(),ciphertext:b64(te.encode(JSON.stringify(body)))}}
export async function markSynced(revision){const r=await get();if(r){r.revision=revision;await put(r)}}
export async function importSyncEnvelope(envelope){const remote=JSON.parse(td.decode(unb64(envelope.ciphertext)));await put({...remote,revision:envelope.revision});return true}

export async function commitMergedRecord(record,revision){await put({...record,revision});return true}
export function envelopeFromRecord(record){const body={v:record.v,kdf:record.kdf,wrappedKey:record.wrappedKey,check:record.check,payload:record.payload};return{version:record.v,revision:Number(record.revision||0),updatedAt:new Date().toISOString(),ciphertext:b64(te.encode(JSON.stringify(body)))}}
