-- Reference schema for a dedicated Aegis Supabase project.
-- Vault payloads are ciphertext generated by clients.
create extension if not exists pgcrypto;

create table if not exists public.accounts (\n  id uuid primary key default gen_random_uuid(),\n  email_normalized text not null unique,\n  auth_verifier text not null,\n  created_at timestamptz not null default now(),\n  disabled_at timestamptz\n);\n
create table if not exists public.profiles (
  user_id uuid primary key references public.accounts(id) on delete cascade,
  display_name text,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.vaults (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.accounts(id) on delete cascade,
  name_ciphertext text not null,
  wrapped_vault_key text not null,
  crypto_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.vault_members (
  vault_id uuid not null references public.vaults(id) on delete cascade,
  user_id uuid not null references public.accounts(id) on delete cascade,
  role text not null check (role in ('owner','admin','editor','viewer')),
  wrapped_member_key text not null,
  created_at timestamptz not null default now(),
  primary key(vault_id,user_id)
);
create table if not exists public.vault_items (
  id uuid primary key default gen_random_uuid(),
  vault_id uuid not null references public.vaults(id) on delete cascade,
  owner_id uuid not null references public.accounts(id) on delete cascade,
  ciphertext text not null,
  nonce text not null,
  crypto_version integer not null default 1,
  item_version bigint not null default 1,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.item_versions (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.vault_items(id) on delete cascade,
  vault_id uuid not null references public.vaults(id) on delete cascade,
  ciphertext text not null,
  nonce text not null,
  crypto_version integer not null,
  item_version bigint not null,
  created_at timestamptz not null default now()
);
create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.accounts(id) on delete cascade,
  label text not null,
  platform text not null,
  public_key text,
  wrapped_device_key text,
  last_seen_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.shares (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.accounts(id) on delete cascade,
  vault_id uuid not null references public.vaults(id) on delete cascade,
  envelope_ciphertext text not null,
  recipient_hint_hash text,
  expires_at timestamptz,
  max_views integer,
  view_count integer not null default 0,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.security_events (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.accounts(id) on delete cascade,
  event_type text not null,
  device_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.recovery_methods (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.accounts(id) on delete cascade,
  method_type text not null,
  envelope_ciphertext text not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create table if not exists public.sync_cursors (
  user_id uuid not null references public.accounts(id) on delete cascade,
  device_id uuid not null,
  cursor bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key(user_id,device_id)
);

create index if not exists vaults_owner_idx on public.vaults(owner_id);
create index if not exists vault_items_vault_idx on public.vault_items(vault_id,updated_at);
create index if not exists vault_items_owner_idx on public.vault_items(owner_id);
create index if not exists vault_members_user_idx on public.vault_members(user_id);
create index if not exists devices_user_idx on public.devices(user_id);
create index if not exists shares_sender_idx on public.shares(sender_id);
create index if not exists security_events_user_idx on public.security_events(user_id,created_at desc);

