import Fastify from'fastify';import cookie from'@fastify/cookie';import cors from'@fastify/cors';import helmet from'@fastify/helmet';import rateLimit from'@fastify/rate-limit';import argon2 from'argon2';import{createHash,randomBytes}from'node:crypto';import pg from'pg';import{z}from'zod';
const app=Fastify({logger:true,trustProxy:true});const db=new pg.Pool({connectionString:process.env.DATABASE_URL});const origin=process.env.APP_ORIGIN||'http://localhost:5173';const pepper=process.env.TOKEN_PEPPER;if(!pepper)throw new Error('TOKEN_PEPPER is required');
await app.register(helmet);await app.register(cors,{origin,credentials:true});await app.register(cookie);await app.register(rateLimit,{max:120,timeWindow:'1 minute'});
const email=z.string().email().max(254).transform(v=>v.trim().toLowerCase());const password=z.string().min(12).max(256);const signup=z.object({email,password,displayName:z.string().trim().max(80).optional()});const login=z.object({email,password});const tokenHash=(v:string)=>createHash('sha256').update(v+pepper).digest('hex');const opaque=()=>randomBytes(32).toString('base64url');
async function session(userId:string,reply:any){const token=opaque(),days=Number(process.env.SESSION_DAYS||30);await db.query('insert into auth_sessions(user_id,token_hash,expires_at) values($1,$2,now()+($3||\' days\')::interval)',[userId,tokenHash(token),days]);reply.setCookie('aegis_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:days*86400});}
async function user(req:any){const t=req.cookies.aegis_session;if(!t)return null;const r=await db.query('select a.id,a.email_normalized,p.display_name from auth_sessions s join accounts a on a.id=s.user_id left join profiles p on p.user_id=a.id where s.token_hash=$1 and s.revoked_at is null and s.expires_at>now() and a.disabled_at is null',[tokenHash(t)]);return r.rows[0]||null}
app.get('/health',async()=>({ok:true}));
app.post('/v1/auth/signup',{config:{rateLimit:{max:8,timeWindow:'15 minutes'}}},async(req,reply)=>{const parsed=signup.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:'Invalid signup data'});const e=email.parse(parsed.data.email);const exists=await db.query('select 1 from accounts where email_normalized=$1',[e]);if(exists.rowCount)return reply.code(409).send({error:'Account already exists'});const hash=await argon2.hash(parsed.data.password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});const c=await db.connect();try{await c.query('begin');const a=await c.query('insert into accounts(email_normalized,password_hash,email_verified_at) values($1,$2,null) returning id,email_normalized',[e,hash]);await c.query('insert into profiles(user_id,display_name) values($1,$2)',[a.rows[0].id,parsed.data.displayName||null]);const verify=opaque();await c.query('insert into email_verification_tokens(user_id,token_hash,expires_at) values($1,$2,now()+interval \'24 hours\')',[a.rows[0].id,tokenHash(verify)]);await c.query('commit');await session(a.rows[0].id,reply);return reply.code(201).send({user:{id:a.rows[0].id,email:e},verificationRequired:true,devVerificationToken:process.env.NODE_ENV==='production'?undefined:verify})}catch(err){await c.query('rollback');throw err}finally{c.release()}});
app.post('/v1/auth/login',{config:{rateLimit:{max:10,timeWindow:'15 minutes'}}},async(req,reply)=>{const parsed=login.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:'Invalid credentials'});const e=email.parse(parsed.data.email);const r=await db.query('select id,password_hash,email_normalized from accounts where email_normalized=$1 and disabled_at is null',[e]);if(!r.rowCount||!await argon2.verify(r.rows[0].password_hash,parsed.data.password))return reply.code(401).send({error:'Invalid credentials'});await session(r.rows[0].id,reply);await db.query('insert into security_events(user_id,event_type) values($1,$2)',[r.rows[0].id,'login']);return{user:{id:r.rows[0].id,email:r.rows[0].email_normalized}}});
app.post('/v1/auth/logout',async(req,reply)=>{const t=req.cookies.aegis_session;if(t)await db.query('update auth_sessions set revoked_at=now() where token_hash=$1',[tokenHash(t)]);reply.clearCookie('aegis_session',{path:'/'});return{ok:true}});
app.get('/v1/auth/me',async(req,reply)=>{const u=await user(req);return u?{user:u}:reply.code(401).send({error:'Unauthenticated'})});
const envelope=z.object({version:z.number().int().min(1).max(10),revision:z.number().int().nonnegative(),baseRevision:z.number().int().nonnegative(),updatedAt:z.string().max(64),ciphertext:z.string().min(1).max(10_000_000)});
app.get('/v1/vault/sync',async(req,reply)=>{const u=await user(req);if(!u)return reply.code(401).send({error:'Unauthenticated'});const r=await db.query('select revision,envelope,updated_at from vault_sync where user_id=$1',[u.id]);return r.rowCount?{revision:Number(r.rows[0].revision),envelope:r.rows[0].envelope,updatedAt:r.rows[0].updated_at}:{revision:0,envelope:null}});
app.put('/v1/vault/sync',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{const u=await user(req);if(!u)return reply.code(401).send({error:'Unauthenticated'});const p=envelope.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'Invalid encrypted envelope'});if(p.data.revision!==p.data.baseRevision+1)return reply.code(409).send({error:'Sync conflict'});const r=await db.query(`insert into vault_sync(user_id,revision,envelope,updated_at) select $1,$2,$3::jsonb,now() where $4=0 on conflict(user_id) do update set revision=excluded.revision,envelope=excluded.envelope,updated_at=now() where vault_sync.revision=$4 returning revision,updated_at`,[u.id,p.data.revision,JSON.stringify(p.data),p.data.baseRevision]);if(!r.rowCount)return reply.code(409).send({error:'Sync conflict'});return{ok:true,revision:Number(r.rows[0].revision),updatedAt:r.rows[0].updated_at}});

const ack=z.object({deviceId:z.string().uuid(),revision:z.number().int().nonnegative()});
app.post('/v1/vault/ack',async(req,reply)=>{const u=await user(req);if(!u)return reply.code(401).send({error:'Unauthenticated'});const p=ack.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'Invalid acknowledgement'});const current=await db.query('select revision from vault_sync where user_id=$1',[u.id]);const revision=Math.min(p.data.revision,Number(current.rows[0]?.revision||0));await db.query('insert into vault_sync_devices(user_id,device_id,ack_revision,last_seen_at) values($1,$2,$3,now()) on conflict(user_id,device_id) do update set ack_revision=greatest(vault_sync_devices.ack_revision,excluded.ack_revision),last_seen_at=now()',[u.id,p.data.deviceId,revision]);const floor=await db.query("select coalesce(min(ack_revision),0) min_ack,count(*) device_count from vault_sync_devices where user_id=$1 and last_seen_at>now()-interval '90 days'",[u.id]);return{ok:true,minAckRevision:Number(floor.rows[0].min_ack),activeDevices:Number(floor.rows[0].device_count)}});
app.post('/v1/auth/verify-email',async(req,reply)=>{const p=z.object({token:z.string().min(20)}).safeParse(req.body);if(!p.success)return reply.code(400).send({error:'Invalid token'});const r=await db.query('update accounts a set email_verified_at=now() from email_verification_tokens t where t.user_id=a.id and t.token_hash=$1 and t.used_at is null and t.expires_at>now() returning a.id',[tokenHash(p.data.token)]);if(!r.rowCount)return reply.code(400).send({error:'Invalid or expired token'});await db.query('update email_verification_tokens set used_at=now() where token_hash=$1',[tokenHash(p.data.token)]);return{ok:true}});
app.post('/v1/auth/forgot-password',{config:{rateLimit:{max:5,timeWindow:'30 minutes'}}},async(req)=>{const p=z.object({email}).safeParse(req.body);if(p.success){const r=await db.query('select id from accounts where email_normalized=$1',[p.data.email]);if(r.rowCount){const t=opaque();await db.query('insert into password_reset_tokens(user_id,token_hash,expires_at) values($1,$2,now()+interval \'30 minutes\')',[r.rows[0].id,tokenHash(t)]);if(process.env.NODE_ENV!=='production')app.log.info({devPasswordResetToken:t},'password reset token')}}return{ok:true}});
app.post('/v1/auth/reset-password',async(req,reply)=>{const p=z.object({token:z.string().min(20),password}).safeParse(req.body);if(!p.success)return reply.code(400).send({error:'Invalid reset data'});const c=await db.connect();try{await c.query('begin');const r=await c.query('select user_id from password_reset_tokens where token_hash=$1 and used_at is null and expires_at>now() for update',[tokenHash(p.data.token)]);if(!r.rowCount){await c.query('rollback');return reply.code(400).send({error:'Invalid or expired token'})}const h=await argon2.hash(p.data.password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});await c.query('update accounts set password_hash=$1 where id=$2',[h,r.rows[0].user_id]);await c.query('update password_reset_tokens set used_at=now() where token_hash=$1',[tokenHash(p.data.token)]);await c.query('update auth_sessions set revoked_at=now() where user_id=$1',[r.rows[0].user_id]);await c.query('commit');return{ok:true}}finally{c.release()}});
await app.listen({host:'0.0.0.0',port:Number(process.env.PORT||8080)});